<?php
if( !function_exists( 'register_field_group' ) ) {
if (file_exists(BEAU_PLUGIN_DIR. '/libs/advanced-custom-fields/acf.php')) {
    require_once(BEAU_PLUGIN_DIR. '/libs/advanced-custom-fields/acf.php');
}
   
    $gallery_cats = get_terms('gallery_category');      

    
    register_field_group(array (
        'id' => 'acf_crew-info',
        'title' => 'Crew Info',
        'fields' => array (
            array (
                'key' => 'field_566005821cdc0',
                'label' => 'Crew job',
                'name' => 'crew_job',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => 'Main actor',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_566007881cdc2',
                'label' => 'Crew Social',
                'name' => 'crew_social',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_566007951cdc3',
                        'label' => 'Screw Social Icon',
                        'name' => 'screw_social_icon',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'fa-facebook',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_566007ef1cdc4',
                        'label' => 'Crew Social Link',
                        'name' => 'crew_social_link',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'http://faceboook.com/beautheme',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'crew',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_discover-info',
        'title' => 'Discover Info',
        'fields' => array (
            array (
                'key' => 'field_566ffc0453068',
                'label' => 'Timeline',
                'name' => 'timeline',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_566ffc1653069',
                        'label' => 'Name',
                        'name' => 'name',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_566ffd005306a',
                        'label' => 'Date',
                        'name' => 'date',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 1900,
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_566ffd2c5306b',
                        'label' => 'Image',
                        'name' => 'image',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_566ffd425306c',
                        'label' => 'Content',
                        'name' => 'content',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-discover.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_discover-origin',
        'title' => 'Discover Origin',
        'fields' => array (
            array (
                'key' => 'field_566ffebedc593',
                'label' => 'Title Origin',
                'name' => 'title_origin',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_566ffeebdc594',
                'label' => 'Name Orgin',
                'name' => 'name_orgin',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5670e2ccf9827',
                'label' => 'Content Origins',
                'name' => 'content_origin',
                'type' => 'wysiwyg',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-discover.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));

    register_field_group(array (
        'id' => 'acf_gallery-film',
        'title' => 'Film gallery',
        'fields' => array (
            array (
                'key' => 'field_565ffdcfc8f60',
                'label' => 'Image list ',
                'name' => 'gallery_film',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_57a9aaeacbbd6',
                        'label' => 'Image',
                        'name' => 'image_gallery_film',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array (
                        'key' => 'field_57a9ab25cbbd7',
                        'label' => 'Video embed url (optional)',
                        'name' => 'video_url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Allow Youtube or Vimeo embed url',
                    ),
                    array (
                        'key' => 'field_57a9ab74cbbd8',
                        'label' => 'Description',
                        'name' => 'short_description_image',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => 'wpautop',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'gallery',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));

    register_field_group(array (
        'id' => 'acf_history-event',
        'title' => 'History Event',
        'fields' => array (
            array (
                'key' => 'field_5667a372e20d4',
                'label' => 'Event',
                'name' => 'event',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5667a3b5e20d5',
                        'label' => 'Event Year',
                        'name' => 'event_year',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5667a3c8e20d6',
                        'label' => 'Event Title',
                        'name' => 'event_title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5667a3e2e20d7',
                        'label' => 'Event Image',
                        'name' => 'event_image',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_5667a3f8e20d8',
                        'label' => 'Event Description',
                        'name' => 'event_description',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Row',
            ),
            array (
                'key' => 'field_5667a6d577b10',
                'label' => 'Today History',
                'name' => 'end_history',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5667a6fe77b11',
                        'label' => 'Year',
                        'name' => 'year',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5667a72077b12',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5667a73a77b13',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-history.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_movie-trailer',
        'title' => 'Movie Trailer',
        'fields' => array (
            array (
                'key' => 'field_565fec3711ab2',
                'label' => 'Video',
                'name' => 'video',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_565fec9c11ab4',
                        'label' => 'Name',
                        'name' => 'name',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_565fec4f11ab3',
                        'label' => 'Image',
                        'name' => 'image-film',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_565fedfe11ab5',
                        'label' => 'Video url',
                        'name' => 'video_url',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'film',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_partner-info',
        'title' => 'Partner Info',
        'fields' => array (
            array (
                'key' => 'field_566e54d4928e9',
                'label' => 'Url',
                'name' => 'url',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '#',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'partner',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_profile-director',
        'title' => 'Profile Director',
        'fields' => array (
            array (
                'key' => 'field_567a885e4a3da',
                'label' => 'Image Cover',
                'name' => 'image_cover',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_565fcfe5affad',
                'label' => 'Profile',
                'name' => 'profile',
                'type' => 'wysiwyg',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
            ),
            array (
                'key' => 'field_565fb850103c8',
                'label' => 'Social',
                'name' => 'social',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_565fb8bb103c9',
                        'label' => 'Icon',
                        'name' => 'social-icon',
                        'type' => 'text',
                        'instructions' => 'Copy from awesome fonts',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'fa-facebook',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_565fb903103ca',
                        'label' => 'Social Url',
                        'name' => 'social-url',
                        'type' => 'text',
                        'instructions' => 'Input your social url',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'http://facebook.com/beautheme',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'director',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_service-template',
        'title' => 'Service Template',
        'fields' => array (
            array (
                'key' => 'field_566be2ee3d924',
                'label' => 'Service',
                'name' => 'service',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_566be3033d925',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_566be34e3d926',
                        'label' => 'Icon',
                        'name' => 'icon',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'fa-ship',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_566be49c3d927',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                    array (
                        'key' => 'field_566be54f78b8c',
                        'label' => 'Image',
                        'name' => 'image',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-service.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_team-info',
        'title' => 'Team Info',
        'fields' => array (
            array (
                'key' => 'field_5665469a15456',
                'label' => ' Job',
                'name' => 'team_job',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => 'Actor',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5665471915459',
                'label' => 'Social',
                'name' => 'team_social',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5665473b1545a',
                        'label' => 'Social Icon',
                        'name' => 'social_team_icon',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'fa-facebook',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_566547c21545b',
                        'label' => 'Social Link',
                        'name' => 'social_team_link',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'http://facebook.com/beautheme/',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'team',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_timeline-director',
        'title' => 'Timeline Director',
        'fields' => array (
            array (
                'key' => 'field_565fd041c2940',
                'label' => 'Timeline',
                'name' => 'timeline',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_565fd087c2941',
                        'label' => 'Date',
                        'name' => 'date',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 1996,
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_565fd0cac2942',
                        'label' => 'Director film',
                        'name' => 'director_film',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'The Death',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_565fd17cc2943',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'director',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_movie-story',
        'title' => 'Movie story',
        'fields' => array (
            array (
                'key' => 'field_565ff0220f2b9',
                'label' => 'Image Movie',
                'name' => 'image_movie',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_565ff0cb0f2bb',
                'label' => 'Text movie',
                'name' => 'text_movie',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => 'Album War of Ages was released in July 2005 on Strike First Records',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_565ff1890f2bd',
                'label' => 'Description',
                'name' => 'description-movie',
                'type' => 'wysiwyg',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'film',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 2,
    ));
    register_field_group(array (
        'id' => 'acf_character-movie',
        'title' => 'Character movie',
        'fields' => array (
            array (
                'key' => 'field_565ff48deeaa7',
                'label' => 'Character',
                'name' => 'character',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_565ff4d0eeaa8',
                        'label' => 'Image',
                        'name' => 'image-character',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_565ff533eeaa9',
                        'label' => 'Name',
                        'name' => 'name-character',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'John Smith',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_565ff57deeaaa',
                        'label' => 'Role',
                        'name' => 'role',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'Protagonist',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_565ff638eeaab',
                        'label' => 'Description',
                        'name' => 'description-character-film',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'film',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 3,
    ));
    register_field_group(array (
        'id' => 'acf_movie-winning',
        'title' => 'Movie Winning',
        'fields' => array (
            array (
                'key' => 'field_565ff8503fccb',
                'label' => 'Winning award',
                'name' => 'winning_award',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_565ff86a3fccc',
                        'label' => 'Image',
                        'name' => 'image-award',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_565ff89a3fccd',
                        'label' => 'winning url',
                        'name' => 'win_award_url',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'http://www.winning-awards.co.uk/',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'film',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 4,
    ));
    register_field_group(array (
        'id' => 'acf_image-categories',
        'title' => 'Image categories',
        'fields' => array (
            array (
                'key' => 'field_568b2fdf29051',
                'label' => 'Image categories',
                'name' => 'image_categories',
                'type' => 'image',
                'instructions' => 'Upload image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 5,
    ));
    register_field_group(array (
        'id' => 'acf_partner-movie',
        'title' => 'Partner Movie',
        'fields' => array (
            array (
                'key' => 'field_565ffbc2aa0c9',
                'label' => 'Film Studio',
                'name' => 'film_studio',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_565ffc34aa0ca',
                        'label' => 'logo',
                        'name' => 'logo-studio',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_565ffc51aa0cb',
                        'label' => 'Studio Url',
                        'name' => 'studio_url',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'http://www.winning-awards.co.uk/',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'film',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 5,
    ));
    register_field_group(array (
        'id' => 'acf_relate-film',
        'title' => 'Relate Film',
        'fields' => array (
            array (
                'key' => 'field_56600cf93a22f',
                'label' => 'Film List',
                'name' => 'film_list',
                'type' => 'relationship',
                'return_format' => 'object',
                'post_type' => array (
                    0 => 'film',
                ),
                'taxonomy' => array (
                    0 => 'all',
                ),
                'filters' => array (
                    0 => 'search',
                ),
                'result_elements' => array (
                    0 => 'post_type',
                    1 => 'post_title',
                ),
                'max' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'director',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 6,
    ));
    register_field_group(array (
        'id' => 'acf_relate-gallery-film',
        'title' => 'Relate Gallery film',
        'fields' => array (
            array (
                'key' => 'field_566009af6a203',
                'label' => 'Gallery List',
                'name' => 'gallery_list',
                'type' => 'relationship',
                'return_format' => 'object',
                'post_type' => array (
                    0 => 'gallery',
                ),
                'taxonomy' => array (
                    0 => 'all',
                ),
                'filters' => array (
                    0 => 'search',
                ),
                'result_elements' => array (
                    0 => 'post_type',
                    1 => 'post_title',
                ),
                'max' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'film',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 6,
    ));
    register_field_group(array (
        'id' => 'acf_cast-and-crew',
        'title' => 'Cast and Crew',
        'fields' => array (
            array (
                'key' => 'field_56d7f1a815fd9',
                'label' => 'Group Ingredient ',
                'name' => 'ingred_group',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_56d7f53e4c04e',
                        'label' => 'Group Ingredient    Name',
                        'name' => 'group_ingredient__name',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_56d7f5704c04f',
                        'label' => 'Ingredient Actor',
                        'name' => 'ingredient_actor',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56d7f58d4c050',
                                'label' => 'Ingredient Actor Name',
                                'name' => 'ingredient_actor_name',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                        ),
                        'row_min' => '',
                        'row_limit' => '',
                        'layout' => 'table',
                        'button_label' => 'Add Row',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'film',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 10,
    ));

    register_field_group(array (
        'key' => 'group_57aaeafdf308e',
        'title' => 'Film style info',
        'fields' => array (
            array (
                'key' => 'field_57aaeb0919ba5',
                'label' => 'Small title',
                'name' => 'small_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_57aaeb2319ba6',
                'label' => 'Main title',
                'name' => 'main_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_57aaeb3219ba7',
                'label' => 'Short description',
                'name' => 'short_description',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-film2.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
    
    register_field_group(array (
        'key' => 'group_57aaeafdf30s8ssde',
        'title' => 'Gallery template seting',
        'fields' => array (
            array (
                'key' => 'field_enable_pagination',
                'label' => 'Enable Pagination',
                'name' => 'enable_pagination',
                'type' => 'select',
                'choices' => array(     
                    0 => 'No' ,
                    1 => 'Yes'
                ),
                'instructions' => '',
                'required' => 0,
                'message' => 0,
            ),
            array (
                'key' => 'field_57fb5f8e2d15f',
                'label' => 'Select Gallery',
                'name' => 'select_gallery',
                'type' => 'post_object',
                'instructions' => 'Have at least 6 galleries to look beauty :D ',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                ),
                'post_type' => array (
                        0 => 'gallery',
                ),
                'taxonomy' => array (
                ),
                'allow_null' => 1,
                'multiple' => 1,
                'return_format' => 'id',
                'ui' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-gallery.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
}
